### ISSUE TITLE
Office pages should work without image

### ISSUE THREAD

**Issue by bwaltz** [ColbyCommunications/colby-college-theme#1]
Right now if there's no featured image, a broken image appears. In the case of no image, the text should fill in the space.

<img width="1312" alt="Screen Shot 2022-10-21 at 2 32 34 PM" src="https://user-images.githubusercontent.com/2333967/197265853-ab2395f3-fef3-4309-bb5f-e1de121908df.png">

**Comment by gregoryspragginsjr** [comment]
@bwaltz This has been addressed in my latest commit at: https://github.com/ColbyCommunications/colby-college-theme/commit/2e8f2736e3e475a025e028cb1616032d313e78fd

Let me know if you like the look here, and close when ready.
