### ISSUE TITLE
Missing active state on People Directory nav item on People Directory page

### ISSUE THREAD

**Issue by bwaltz** [ColbyCommunications/colby-college-theme#14]
https://master-7rqtwti-ouiqvb5juucvu.us-4.platformsh.site/people/people-directory/

See image below:

![People_Archive_-_Colby_College](https://user-images.githubusercontent.com/2333967/197850190-e857abcd-6324-4830-8e69-6bd9957e752c.png)

Of course, I'm not sure I'm adding it in correctly backend. I have it as a hardcoded url like 

![Screen Shot 2022-10-25 at 2 14 39 PM](https://user-images.githubusercontent.com/2333967/197850398-782e71b9-d3d9-46bb-8003-547f5982c7f0.png)

I couldn't find a page for it in the menus UI either:

![Screen Shot 2022-10-25 at 2 15 41 PM](https://user-images.githubusercontent.com/2333967/197850556-8e4d2f17-a48b-424f-a7c1-0e70fc44ac7e.png)

**Comment by gregoryspragginsjr** [comment]
@bwaltz you were very close here. Theres actually a way to add direct links to a `Post Type Archive` IE the people archive to the menu without having to use a custom link. For some reason, it was hidden in your `Screen Options`, so I reactivated it and replaced that menu item for you the correct way. This should be all good now, so Ill be closing it for you.
