### ISSUE TITLE
Scroll bars noticed on Section Navigation

### ISSUE THREAD

**Issue by bwaltz** [ColbyCommunications/colby-college-theme#15]
https://master-7rqtwti-ouiqvb5juucvu.us-4.platformsh.site/academics/

![Screen Shot 2022-10-25 at 2 19 43 PM](https://user-images.githubusercontent.com/2333967/197851308-42193eec-2f7d-46f3-9a06-0ef94ccf29d0.png)

**Comment by bwaltz** [comment]
My normal work setup:

Chrome 106, Mac M1

**Comment by gregoryspragginsjr** [comment]
@bwaltz Im still not able to recreate this anomaly on my end specifically on mac (I do see it on windows). Can you confirm you're not using any extensions or system preferences that might be forcing the scrollbar into visibility? In the interim, I've pushed a commit that MIGHT do the trick at: https://github.com/ColbyCommunications/colby-college-theme/commit/09ff3ce0ed23725dcb0d8046a1dee09ebed20cfe

**Comment by bwaltz** [comment]
@gregoryspragginsjr yes! This works! Closing.
