### ISSUE TITLE
Is it possible to make the Section Navs automated?

### ISSUE THREAD

**Issue by bwaltz** [ColbyCommunications/colby-college-theme#16]
Instead of manually adding links to the Section Nav blocks, is it possible for them to pull automatically from child pages (one level deep)?

It seems that the left sidebar nav are automatically generated and the Section Nav blocks contain the same links.

**Comment by gregoryspragginsjr** [comment]
@bwaltz we can accommodate this, but given that the `section-nav` is technically only used twice throughout the entire site (Academics and People landing pages) I'm gonna leave it as low priority unless you envision a scenario in which your deploying it much more often.

**Comment by bwaltz** [comment]
Sounds good, @gregoryspragginsjr.

**Comment by bwaltz** [comment]
@gregoryspragginsjr don't do this yet. We may need to re-evaluate internally.
