### ISSUE TITLE
Changes to table filtering

### ISSUE THREAD

**Issue by bwaltz** [ColbyCommunications/colby-college-theme#17]
Is it possible to slightly change how table filtering works? Currently, the default is to display all results. Then the user would click on a filter, like "Fall" for example, in the courses table. The user would then need to click "Fall" again to turn off the filter.

Can we instead have an "All" filter option that is active by default and then the user can click on the other filtering options if they need. In this case, the filters act like tabs and one is always active. If the user wanted to "turn off" filtering, they'd just click on "All" again.

**Comment by bwaltz** [comment]
![Screen Shot 2022-10-25 at 4 34 50 PM](https://user-images.githubusercontent.com/2333967/197877508-a315b501-ed78-4136-8797-5ed82792167f.png)

**Comment by bwaltz** [comment]
This goes the same for the majors and minors table.

**Comment by gregoryspragginsjr** [comment]
@bwaltz Not a problem. I've just pushed a commit to facilitate this. The `All` button is there by default. You can now either click on `All` OR just unclick an option to toggle the filter. Either works.

https://github.com/ColbyCommunications/colby-college-theme/commit/c4ddfafc581709343ff03e26265a425c399100f1

As always, verify and let me know if this works for you before closing.
