### ISSUE TITLE
Need H1 on post single page

### ISSUE THREAD

**Issue by bwaltz** [ColbyCommunications/colby-college-theme#18]
For example:

https://master-7rqtwti-ouiqvb5juucvu.us-4.platformsh.site/art/garry-mitchell-associate-professor-of-art-has-17-works-on-view-at-the-portland-press-hotel/

I see the title in the bread crumb but not an overarching H1 tag for this type of page. Can we add it?

**Comment by gregoryspragginsjr** [comment]
@bwaltz for all posts, there is a context field group at the bottom which would populate your hero in these instances. You'll need to add that for news articles to be complete from a front-end perspective. Ill populate this as an example.

**Comment by bwaltz** [comment]
@gregoryspragginsjr Ok, I see. This will be challenging to achieve since the vast majority of our posts will be imported. I also think this is too much to ask of our editors to add details to that context field group. Is there a way we can simplify the single post template to just use the post title as the H1? We can keep the date. I also don't think we even need the paragraph or the subheading.

**Comment by bwaltz** [comment]
@gregoryspragginsjr I discussed this with Andrew as well. We still want to proceed with everything you and I discussed this morning about simplifying the post single page.

One other thing came up. Is there a way to remove the large indentation on the left on post pages? I think that space is normally reserved for the sidebar, but for these pages we won't have one. Instead we'd like to display the body flush left, like, for example:

![Screen Shot 2022-10-27 at 12 38 00 PM](https://user-images.githubusercontent.com/2333967/198349192-a2e031d1-827e-463f-9447-4b01a13fcaed.png)

Is this possible?

**Comment by gregoryspragginsjr** [comment]
@bwaltz This change has been applied via a few commits including: https://github.com/ColbyCommunications/colby-college-theme/commit/957fe8a423a822109c5bc558472610955bc9204e

In regards to your comment, I've also opened up the template to go full width specficially for `posts` but be advised, in doing this you no longer have access to the sidebar `widgets` components without additional conditionals written on my end. Can you confirm whether or not you feel you'll need those for the future? My thinking was, considering your earlier request to remove custom context, you likely wouldnt need `widgets` either so we should be good, but didnt wanna assume.

If the answer is no, then we can go ahead and close this issue after confirming the changes.

**Comment by gregoryspragginsjr** [comment]
@bwaltz Im seeing this too on staging, but cannot recreate locally. This would most surely be a hosting or .htaccess redirect issue. I'd start investigating there. Are you deploying any redirects on platform.sh?
