### ISSUE TITLE
Remove stock content editor field on People posts

### ISSUE THREAD

**Issue by bwaltz** [ColbyCommunications/colby-college-theme#19]
We've chosen to use the bio custom field instead. Is it possible to remove the stock content editor field?

![Edit_Person_“Jennifer_Richards”_‹_Colby_College_—_WordPress](https://user-images.githubusercontent.com/2333967/198301168-981f5f89-253a-4042-810d-00955dbe4c27.png)

**Comment by gregoryspragginsjr** [comment]
@bwaltz this is complete as of: https://github.com/ColbyCommunications/colby-college-theme/commit/c7d3a0ea6e95910a9b3456e8e74ab58ec37523e0

Double check and close this issue when ready
