### ISSUE TITLE
Sometimes the circular images on the People Directory page table view look weird

### ISSUE THREAD

**Issue by bwaltz** [ColbyCommunications/colby-college-theme#2]
See below:

<img width="919" alt="Screen Shot 2022-10-21 at 3 23 26 PM" src="https://user-images.githubusercontent.com/2333967/197274104-59862786-db73-416b-90d8-5840a3f37d9c.png">
<img width="786" alt="Screen Shot 2022-10-21 at 3 23 12 PM" src="https://user-images.githubusercontent.com/2333967/197274110-a88a8f31-d4a8-435b-8d19-a5a8b12e1386.png">

**Comment by gregoryspragginsjr** [comment]
@bwaltz good catch. I've applied a forced height here a long with some padding for aesthetics. Commit is here: https://github.com/ColbyCommunications/colby-college-theme/commit/42110f66a22c69a750ea93f8ff7cfcd888521115 Please confirm and close this issue when ready.
