### ISSUE TITLE
Embed for Registrar Form

### ISSUE THREAD

**Issue by gregoryspragginsjr** [ColbyCommunications/colby-college-theme#21]
Recieved general embed form. We will need an embed form specifically for the registrar page under academics.

**Comment by bwaltz** [comment]
@gregoryspragginsjr Talked to Andrew about this. We can't find the comp for the "Contact the Registrar" form anywhere. We aren't convinced that we really need one anyway.

What we can do instead is just add an "Registrar" option to the general contact Colby form.
