### ISSUE TITLE
Staff listing images on department pages

### ISSUE THREAD

**Issue by bwaltz** [ColbyCommunications/colby-college-theme#22]
![Screen Shot 2022-10-27 at 10 48 25 AM](https://user-images.githubusercontent.com/2333967/198322038-55568e4c-f02f-418a-bebe-ac7452d3e63d.png)

**Comment by bwaltz** [comment]
@gregoryspragginsjr Talked to Andrew about this. He wants to see if it's possible to align staff item with their names. In other words, for each row, the names should be aligned.

For example:

![Screen_Shot_2022-10-27_at_10_48_25_AM](https://user-images.githubusercontent.com/2333967/198343174-b1806900-296f-4076-a7ba-bbb750d302e6.png)

Let me know if you think this is doable.

**Comment by gregoryspragginsjr** [comment]
@bwaltz the commit I made to fix https://github.com/ColbyCommunications/colby-college-theme/issues/26 should address this.
