### ISSUE TITLE
How to approach hero headings on department pages

### ISSUE THREAD

**Issue by bwaltz** [ColbyCommunications/colby-college-theme#23]
![Screen Shot 2022-10-27 at 10 59 50 AM](https://user-images.githubusercontent.com/2333967/198325533-0741f5cb-3d5d-4119-a2d7-fddfeadc2791.png)

**Comment by bwaltz** [comment]
@gregoryspragginsjr Talked to Andrew about this. The best option for us would be to use everything as is, but just swap the h1 and h2. We think it would be best for the page title, the top small text to be the H1 (styled the same), and the larger text to be the H2.

Let me know if this is doable. If not, we can talk internally about other options.

**Comment by gregoryspragginsjr** [comment]
@bwaltz Okay, this change has been applied via a few commits, including the following: https://github.com/ColbyCommunications/colby-college-theme/commit/957fe8a423a822109c5bc558472610955bc9204e

Please be advised, this move affects both the standard `hero` component (featured on most pages and posts) as well as the `overlay-hero` (featured on the People page and a few other places). 

Please verify and close when ready.

**Comment by bwaltz** [comment]
@gregoryspragginsjr, this works everywhere BUT post pages. On post pages, we really need the post title to be the H1.

https://master-7rqtwti-ouiqvb5juucvu.us-4.platformsh.site/art/plesch-presents-paper-at-international-conference-on-british-artist-tom-phillips/

Sorry if this causes some headaches. It seems on most other pages the page name is going into that spot, but on post pages we're using the date there instead.

Not sure if we need to create a new hero element just for posts.

**Comment by gregoryspragginsjr** [comment]
@bwaltz no worries! I see what you're referring to and have pushed a commit to facilitate posts better at: https://github.com/ColbyCommunications/colby-college-theme/commit/5a2d33c6680db398f534b75423ee38828b8a5be7

The second heading on posts will now be marked as the `h1` whereas everywhere else, they will be `h2`
