### ISSUE TITLE
Changes aren't picked up by the preview

### ISSUE THREAD

**Issue by bwaltz** [ColbyCommunications/colby-college-theme#25]
We're finding that we need to save our changes for them to show on the page. Preview doesn't work as intended.

**Comment by gregoryspragginsjr** [comment]
@bwaltz this is a weird one that I'm not able to replicate in my local environment; previews still seem to function for me (Preview in a new tab button to be specific. Top right of the dash).

Keep in mind, staging has a fair amount of external plugins / differences that could be negatively impacting Wordpress and the Gutenberg REST API. If there is an issue with preview, I'd start investigating that first. We can collaborate on this if necessary; just give me a ring.
