### ISSUE TITLE
Use placeholder image for directory teasers and people directory table

### ISSUE THREAD

**Issue by bwaltz** [ColbyCommunications/colby-college-theme#26]
Sent the placeholder image through email. This is for when a person has no image. The placeholder looks like this:

![colby-buildings-placeholder (1) (1)](https://user-images.githubusercontent.com/2333967/198727154-305b2847-1f80-4536-813b-2663a0b7ce57.jpeg)

**Comment by gregoryspragginsjr** [comment]
@bwaltz a recent commit I've pushed should cover this: https://github.com/ColbyCommunications/colby-college-theme/commit/8bc7d3573cd2f29c3283dd9c29d78c1fb9248e2e 

Let me know if things look good on your end.

**Comment by bwaltz** [comment]
This fixes people directory table. We still need the placeholde to load in the article grid (faculty listing sections in academic depts) if no other image exists for a person:

https://master-7rqtwti-ouiqvb5juucvu.us-4.platformsh.site/academics/departments-and-programs/art/

**Comment by gregoryspragginsjr** [comment]
@bwaltz I have now applied placeholders to people being pulled in to directory pages. Please be advised, this will only work for `people` being pulled directly using the `posts` dropdown on the admin page. When manually adding people to these pages, you'll have to manually pick images still. Please verify on your end and close when ready.

**Comment by bwaltz** [comment]
@gregoryspragginsjr Awesome! Thanks! How come I don't see any placeholder images on these pages?

https://master-7rqtwti-ouiqvb5juucvu.us-4.platformsh.site/academics/departments-and-programs/art/
https://master-7rqtwti-ouiqvb5juucvu.us-4.platformsh.site/academics/departments-and-programs/science-technology-and-society/

**Comment by gregoryspragginsjr** [comment]
@bwaltz be sure to set your image orientation to `profile` for these grid items to default. I've set an example at https://master-7rqtwti-ouiqvb5juucvu.us-4.platformsh.site/academics/departments-and-programs/art/
