### ISSUE TITLE
People directory pagination broken

### ISSUE THREAD

**Issue by bwaltz** [ColbyCommunications/colby-college-theme#27]
https://master-7rqtwti-ouiqvb5juucvu.us-4.platformsh.site/people/people-directory/

<img width="1041" alt="Screen Shot 2022-10-31 at 10 37 59 AM" src="https://user-images.githubusercontent.com/2333967/199034300-f013aad2-bc6b-412f-993c-8764965ef685.png">

**Comment by gregoryspragginsjr** [comment]
@bwaltz my most recent commit should address this problem at https://github.com/ColbyCommunications/colby-college-theme/commit/2cfddd649d8dc926b5fddf70d291c6df68ce9cf2
