### ISSUE TITLE
Alphabetize Departments and Programs

### ISSUE THREAD

**Issue by GioAceto** [ColbyCommunications/colby-college-theme#28]
Departments and programs should be alphabetized:
[https://master-7rqtwti-ouiqvb5juucvu.us-4.platformsh.site/academics/departments-and-programs/](url)

**Comment by gregoryspragginsjr** [comment]
@GioAceto this change should be reflectant as of my latest commit at: https://github.com/ColbyCommunications/colby-college-theme/commit/aff83d601f18084787baa9d33f61fe780127a916

Please verify and close this issue when ready.

**Comment by bwaltz** [comment]
@GioAceto this looks to be completed: https://master-7rqtwti-ouiqvb5juucvu.us-4.platformsh.site/academics/departments-and-programs/. Closing.
