### ISSUE TITLE
Javascript Error on this page

### ISSUE THREAD

**Issue by bwaltz** [ColbyCommunications/colby-college-theme#3]
https://master-7rqtwti-ouiqvb5juucvu.us-4.platformsh.site/people/people-directory/catherine-besteman/

We'll probably need to figure this out together.

**Comment by gregoryspragginsjr** [comment]
@bwaltz lets connect when you've got a chance

**Comment by bwaltz** [comment]
@gregoryspragginsjr when are you free next?

I can do all morning tomorrow and all Friday.

**Comment by gregoryspragginsjr** [comment]
@bwaltz I have availability all morning tomorrow as well. Lets just connect then
