### ISSUE TITLE
Ordered lists not styled

### ISSUE THREAD

**Issue by bwaltz** [ColbyCommunications/colby-college-theme#32]
For example, https://master-7rqtwti-ouiqvb5juucvu.us-4.platformsh.site/academics/course-catalogue/african-american-studies-requirements/

![_FINISHED__American_Studies_Requirements_-_Colby_College](https://user-images.githubusercontent.com/2333967/199311411-2c1dfd83-753b-486c-bb16-a224c322e9f4.png)

**Comment by gregoryspragginsjr** [comment]
@bwaltz this should be rendering fine now as of my latest commit at: https://github.com/ColbyCommunications/colby-college-theme/commit/1b1d68c7eb539f5b1299fada3edfe0d5bd2167d8
