### ISSUE TITLE
Timber context false in add_to_context() for group users

### ISSUE THREAD

**Issue by bwaltz** [ColbyCommunications/colby-college-theme#34]
I've assigned both of us because we'll most likely need to work on this together. 

Here's where it's failing and what the error page looks like:
https://github.com/ColbyCommunications/colby-college-theme/blob/master/functions.php#L452

![Screen Shot 2022-11-02 at 11 15 04 AM](https://user-images.githubusercontent.com/2333967/199527875-17c41486-2a8a-42d5-8ca2-a7bcb39e3e25.png)

**Steps to reproduce:**

1. Login to the stage site as an administrator.
2. Go to the Users screen
3. Switch to user "sncantre"
4. Go to homepage, or any page on the frontend

**Comment by gregoryspragginsjr** [comment]
@bwaltz As discussed, we've gone ahead and removed `groups` taxonomy as of this latest commit: https://github.com/ColbyCommunications/colby-college-theme/commit/1fe5f026f889d57ae73207c57e2dd631a56bf93f
