### ISSUE TITLE
Add heading above current courses table on directory profiles

### ISSUE THREAD

**Issue by bwaltz** [ColbyCommunications/colby-college-theme#36]
We noticed that there wasn't a heading describing the table. We'd like it to say "Current Courses".

![Screen Shot 2022-11-03 at 11 05 45 AM](https://user-images.githubusercontent.com/2333967/199758264-2fa16065-e360-4b20-84ef-2ab9cf0d40f3.png)

**Comment by gregoryspragginsjr** [comment]
@bwaltz I've introduced a small commit to address this at: https://github.com/ColbyCommunications/colby-college-theme/commit/ae8b60236dc83098c0e179f406540865ab884887

Verify and close when ready
