### ISSUE TITLE
Do we need the accordion block?

### ISSUE THREAD

**Issue by bwaltz** [ColbyCommunications/colby-college-theme#37]
Noticed that there's an accordion block developed by you guys. It doesn't appear to work because when I add it I get:

![Screen Shot 2022-11-03 at 11 52 59 AM](https://user-images.githubusercontent.com/2333967/199769897-f875c4d5-be6f-4bcb-af56-c490c4d1eb8d.png)

Maybe we can remove it?

**Comment by gregoryspragginsjr** [comment]
@bwaltz We do not (unless you'd like one). This is a super compliant accordion that I typically bundle with every project just for testing purposes. Our design did not facilitate an accordion to Colby, so we can remove this.

**Comment by bwaltz** [comment]
@gregoryspragginsjr sweet, let's do that.

**Comment by bwaltz** [comment]
@gregoryspragginsjr so sorry about this ☹️ . We actually do want this functionality. We could really use an accordion for content clean-up.

**Comment by gregoryspragginsjr** [comment]
@bwaltz No problem. We've added a custom accordion to your block options as of this commit: https://github.com/ColbyCommunications/colby-college-theme/commit/c370ab9442b8f99c3ee16a9f61f318679fef6601

I've also added the necessary fields to staging. This particular component is best used within the `page_with-sidebar.twig` template. Give it a try and let me know your thoughts. Close when ready.

**Comment by bwaltz** [comment]
@gregoryspragginsjr I pulled. Is this the correct field group? https://master-7rqtwti-ouiqvb5juucvu.us-4.platformsh.site/wp/wp-admin/post.php?post=19420&action=edit

It doesn't look like the fields are all there, judging from what's in the twig file.

**Comment by gregoryspragginsjr** [comment]
@bwaltz Hey Brandon, that is indeed the correct group. Something seems to have happened to my fields. Give me a moment to sort them out.

**Comment by gregoryspragginsjr** [comment]
@bwaltz Update: You should be able to see the fields now.

**Comment by bwaltz** [comment]
I added an accordion to this page at the bottom: https://master-7rqtwti-ouiqvb5juucvu.us-4.platformsh.site/visitors/explore-maine/

I'm getting a js error:

<img width="900" alt="Screen Shot 2022-11-16 at 8 12 20 PM" src="https://user-images.githubusercontent.com/2333967/202329721-6b29e2c2-269d-42f9-b827-0bf766058fa9.png">

**Comment by gregoryspragginsjr** [comment]
@bwaltz appears to be an encoding issue. One moment.

**Comment by gregoryspragginsjr** [comment]
@bwaltz when you're ready, you can run composer and give this page another swing. Encoding issues should be addressed.
