### ISSUE TITLE
Current Courses table: When no matching items found for a filter (fall, spring, jan) the table defaults to all

### ISSUE THREAD

**Issue by bwaltz** [ColbyCommunications/colby-college-theme#39]
Good examples of this are:

https://master-7rqtwti-ouiqvb5juucvu.us-4.platformsh.site/academics/departments-and-programs/geology/academic-program/courses/
https://master-7rqtwti-ouiqvb5juucvu.us-4.platformsh.site/academics/departments-and-programs/art/current-courses/

Art, for example, has no Jan courses in the data. Geology doesn't have any Jan or spring courses in the data.

**Comment by gregoryspragginsjr** [comment]
@bwaltz I believe this issue has been indirectly addressed as of our new dropdown feature at: https://github.com/ColbyCommunications/colby-college-theme/commit/4f1122e056aa69fda62012121666a1f9f220d2e6

Please confirm and close when ready.

**Comment by bwaltz** [comment]
@gregoryspragginsjr I don't think this is fixed. 

For example, Art has no Jan courses at all in the data and it looks like it's still showing all:

https://master-7rqtwti-ouiqvb5juucvu.us-4.platformsh.site/academics/departments-and-programs/art/academic-program/courses/

**Comment by bwaltz** [comment]
Also, since now we have the department dropdown, there are only 4 Jan courses (which is correct, according to the data).

You can see it by filtering by January in the full table here:

https://master-7rqtwti-ouiqvb5juucvu.us-4.platformsh.site/academics/course-catalogue/

**Comment by gregoryspragginsjr** [comment]
@bwaltz it looks like you guys may have changed how the course catalogue API works over night. Previously, we were using `sess` to pull course semester offering (Fall, Spring, Jan). As of this morning, it looks like you guys have changed it to a string stored in `sessOffered`. This is kind of a big shift that is breaking the filter / data mapping on my end.

Can you guys confirm? Thanks in advance.

**Comment by bwaltz** [comment]
Yes, I'm sorry. We just changed this within the last hour or so. That could be the culprit. We were finding that the course data was incomplete, so we reached out to our IT partners. For example, there were 4 janplan courses before, now there are 150.

The `sessOffered` property should now be filled every time.

The biggest shift was how that `sessOffered` data is now presented and the values. It is now a comma-separated list ("sessOffered": "FA,SP"). I believe that now the values are FA = Fall, SP = Spring and JP = Janplan. Sorry for the inconvenience, but the data should be much more complete now.

**Comment by gregoryspragginsjr** [comment]
@bwaltz additional logic has been added here to facilitate the changes you guys made to the API, and sessions should now be fixed when filtering. Please verify and close when ready: https://github.com/ColbyCommunications/colby-college-theme/commit/4be300c405155159b750362df4f69b672a2adedb
