### ISSUE TITLE
Pull menus by slug rather than by id

### ISSUE THREAD

**Issue by bwaltz** [ColbyCommunications/colby-college-theme#4]
Because the menus (main menu, utility nav, and footer nav) are currently broken.

**Comment by gregoryspragginsjr** [comment]
@bwaltz this issue should be resolved as of my latest commit at https://github.com/ColbyCommunications/colby-college-theme/commit/0fc778d54c08c500e4dbe7b7fc675aad9f7ba722 Please let me know if things are good on your end and close this issue when ready.

**Comment by bwaltz** [comment]
@gregoryspragginsjr Looks good, thank you! I've started adding the menus. You can check them out here:

https://master-7rqtwti-ouiqvb5juucvu.us-4.platformsh.site/

I am noticing a framing issue I think on the main menu (notice the bar on the right):
![Screen Shot 2022-10-25 at 9 43 25 AM](https://user-images.githubusercontent.com/2333967/197790093-d94eefc4-d99c-49d4-95d3-2e3a048e9a52.png)

**Comment by gregoryspragginsjr** [comment]
@bwaltz Sounds good. We can close this. We have a separate issue ticket floating around regarding these random scroll bars, and will address it there.
