### ISSUE TITLE
Editor Alignment Issues

### ISSUE THREAD

**Issue by GioAceto** [ColbyCommunications/colby-college-theme#49]
When aligning images and text, clearing is not happening. Elements below become nested, requiring the use of a spacer block in order to break out of the float.

<img width="1014" alt="Screen Shot 2022-11-16 at 9 54 23 AM" src="https://user-images.githubusercontent.com/55949483/202214820-66b64938-f70b-44af-a6df-854793ffa07b.png">

**Comment by bwaltz** [comment]
@GioAceto can you send me the url where this is happening?

**Comment by bwaltz** [comment]
This should be fixed by the new blocks and style system.
