### ISSUE TITLE
Encode HTML entities in HP news carousel

### ISSUE THREAD

**Issue by bwaltz** [ColbyCommunications/colby-college-theme#5]
<img width="690" alt="Screen Shot 2022-10-24 at 3 06 10 PM" src="https://user-images.githubusercontent.com/2333967/197605769-c7acc0df-060f-4cec-9602-6e36d0ea9a3b.png">

**Comment by gregoryspragginsjr** [comment]
@bwaltz this has been addressed in my latest commit at: https://github.com/ColbyCommunications/colby-college-theme/commit/f403b5ceba10c15c60f6df44d74e24ed7b13294b Please confirm and close when ready
