### ISSUE TITLE
Office Detail Not Showing in Preview

### ISSUE THREAD

**Issue by GioAceto** [ColbyCommunications/colby-college-theme#51]
**Preview**
![Screen Shot 2022-12-01 at 11 18 31 AM](https://user-images.githubusercontent.com/55949483/205104661-c7290866-18b9-468c-988f-0f9096b0e228.png)

**Actual**
![Screen Shot 2022-12-01 at 11 18 41 AM](https://user-images.githubusercontent.com/55949483/205104670-bf89b414-0d49-4931-8f93-0f649d116d32.png)

**Comment by GioAceto** [comment]
Hero images not showing preview either

**Comment by bwaltz** [comment]
@gregoryspragginsjr do you know why this is happening or have you seen this before? The fields for address, phone, etc are coming through as NULL when doing a preview, thus preventing them from displaying.

<img width="692" alt="Screen Shot 2022-12-12 at 1 24 13 PM" src="https://user-images.githubusercontent.com/2333967/207124722-adef625e-bfe7-4a70-a3db-241f34fa6c0a.png">

<img width="338" alt="Screen Shot 2022-12-12 at 1 25 05 PM" src="https://user-images.githubusercontent.com/2333967/207124748-4348b3f4-374f-4480-88b4-6b0565be8b80.png">

**Comment by gregoryspragginsjr** [comment]
@bwaltz @GioAceto hey fellas, sorry for the late chime in here. I have very little idea why this would be occurring, and due to this particular feature not working locally (if you recall, my local DB does not sync directory data as I think I'd need to be whitelisted somehow), I don't have a point of reference to properly address it.

If you'd like an extra set of eyes here, I'll need assistance with the local setup.

**Comment by bwaltz** [comment]
@gregoryspragginsjr for your edification, I ended up checking in with the Timber team on this issue. Here's what they said:

https://github.com/timber/timber/issues/2694

I'll keep looking into it.

**Comment by bwaltz** [comment]
Closing this task in favor of the workaround documented here:

https://support.advancedcustomfields.com/forums/topic/custom-fields-on-post-preview/

This appears to be a known ACF gutenberg issue. We will keep tabs on the discussions and pull in a solution when it becomes available.

**Comment by Levdbas** [comment]
As reported [here](https://support.advancedcustomfields.com/forums/topic/custom-fields-on-post-preview/) this is an ACF issue. Closing it here.
