### ISSUE TITLE
Can't Close Search

### ISSUE THREAD

**Issue by GioAceto** [ColbyCommunications/colby-college-theme#55]

**Comment by bwaltz** [comment]
@GioAceto is this because of the top black admin bar when logged in?

**Comment by GioAceto** [comment]
> @GioAceto is this because of the top black admin bar when logged in?

Yeah looks like it. Never thought to check that.

**Comment by bwaltz** [comment]
@GioAceto I've moved the close button down to get around the admin bar, mostly

![Screen Shot 2022-12-05 at 3 55 50 PM](https://user-images.githubusercontent.com/2333967/205741135-ccc6264d-64bb-4d8e-ac99-93e374e937b8.png)

If it looks good, feel free to close.
