### ISSUE TITLE
Overflow with Hero Header

### ISSUE THREAD

**Issue by GioAceto** [ColbyCommunications/colby-college-theme#60]
White space showing on small mobile views on the right side. It appears to be isolated to pages using the hero header. I had different results using incognito.

Example using Samsung S8+

![Screen Shot 2022-12-06 at 11 13 50 AM](https://user-images.githubusercontent.com/55949483/205964335-ce009bd2-2c42-4f1e-a2ef-fa93c4da1ee2.png)

**Comment by bwaltz** [comment]
@GioAceto this is what I get on incognito Samsung S8

<img width="588" alt="Screen Shot 2022-12-07 at 9 07 28 AM" src="https://user-images.githubusercontent.com/2333967/206200470-4cd409f9-4d5a-4735-9a6f-5ee44e048c47.png">

Did you have a different experience on incognito?

**Comment by GioAceto** [comment]
Yes, I don't see the white space in incognito but I do in a normal browser window.

**Comment by bwaltz** [comment]
@GioAceto It looks to be just an admin bar issue, for when you're logged in. I was able to test it by display none. The overflow seemed to go away:

![Screen Shot 2022-12-07 at 10 00 10 AM](https://user-images.githubusercontent.com/2333967/206213640-75215b22-da7d-4a74-bf98-32d73edca1c1.png)

**Comment by bwaltz** [comment]
@GioAceto I'm going to close this. Feel free to re-open if needed.
