### ISSUE TITLE
Question: Pixelated Hero Image on People page

### ISSUE THREAD

**Issue by bwaltz** [ColbyCommunications/colby-college-theme#61]
The image we're using is huge: https://master-7rqtwti-ouiqvb5juucvu.us-4.platformsh.site/wp-content/uploads/2022/10/container-19.jpg

However, it is quite pixelated on the people page: https://master-7rqtwti-ouiqvb5juucvu.us-4.platformsh.site/people/

Do you know why?

**Comment by gregoryspragginsjr** [comment]
@bwaltz I'm gonna boost the resolution used for heros sitewide. This is 100% a result of a too finely cropped image sizing in `functions.php`. Although we are aiming for lightning fast load times, the 1280px width I have set here is entirely too small. Expect a commit shortly amending this, and a few other sizes. We'll probably boost it to 2400px wide.

**Comment by gregoryspragginsjr** [comment]
@bwaltz Update: I've pushed a commit here that should do the trick. We may need to reupload or toggle the image in the CMS after running your next composer.

**Comment by bwaltz** [comment]
@gregoryspragginsjr It's still pixelated even after a re-upload of that image.

https://master-7rqtwti-ouiqvb5juucvu.us-4.platformsh.site/people/

I wonder if the template's not using the correct size?

**Comment by gregoryspragginsjr** [comment]
@bwaltz that could indeed be it. Let me take a look then.

**Comment by gregoryspragginsjr** [comment]
@bwaltz Update: Try now. I forgot that we updated these `overlay-hero` to support full video. That video component was what needed to be updated to support larger thumbnail sizes.
