### ISSUE TITLE
Left nav not visible sometimes because of Publishpress Groups

### ISSUE THREAD

**Issue by bwaltz** [ColbyCommunications/colby-college-theme#68]

**Comment by GioAceto** [comment]
- [ ] Left sidebar page navigation is working correctly for users (visible and functioning everywhere on the site).
- [ ] Users can only view posts for their groups in WP
- [ ] Users can only view pages for their groups in WP
- [ ] Users can only add and edit posts for their groups
- [ ] Users can only edit pages for their groups
- [ ] Users can be added and removed from groups

**Comment by bwaltz** [comment]
I tested this with a random sample of 10 users and this appears to be fixed.
