### ISSUE TITLE
Embed for Contact form

### ISSUE THREAD

**Issue by bwaltz** [ColbyCommunications/colby-college-theme#7]
Embed contact form on the contact page

**Comment by gregoryspragginsjr** [comment]
@bwaltz Embed for the contact form should now be coming in properly styled as of this commit: https://github.com/ColbyCommunications/colby-college-theme/commit/94156edeefa05811269869878ce50f683c510631

You should be seeing this when placing an embed in any page situated with the `Page with Sidebar` template.

<img width="1440" alt="Screen Shot 2022-10-25 at 4 22 56 PM" src="https://user-images.githubusercontent.com/10871717/197874327-9c53baca-0c95-4741-bd5d-32e6ee99c917.png">

Be advised, the max-width for this thing is set for 540px intentionally to better follow the original design. Any accommodating context can be placed above the embed via the editor as you would with any other component. Let me know how this looks and close when ready.

**Comment by gregoryspragginsjr** [comment]
@bwaltz just a heads up; I've actually added this page for you at: https://master-7rqtwti-ouiqvb5juucvu.us-4.platformsh.site/academics/registrar/

Please review the form there
